spring:
  datasource:
    url: jdbc:mysql://localhost:3306/web #Нужно указать вашу БД
    username: root # пользователь который указат у вас при создании БД
    password: 12345 # пароль который указат у вас при создании БД
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: never
  thymeleaf:
    cache: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 200KB
      max-file-size: 50MB
      max-request-size: 50MB
server:
  port: 8080

